import Nav from '@/components/nav/Nav';
import Footer from '@/components/footer/Footer';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <dl>
        <dt>title</dt>
        <dd>desc</dd>
      </dl>
      <Footer />
    </>
  );
}
